### ISSUE TITLE
DIDComm message URL format

### ISSUE THREAD

**Issue by tplooker** [hyperledger/aries-rfcs#146]
Currently in the [did-exchange-protocol](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange) we define a URL format that connection invitations can be formatted to. This URL can then optionally be transmitted as is or encoded to a QR-Code.

As a reminder, the current format defined in this RFC is as follows

`https://<domain>/<path>?c_i=<invitationstring>`

Whereby the invitation string is a base64 URL safe encoding of a connection invitiation message.

Following this definition, the notion of more ephemeral interactions was introduced, where by protocols such as the [presentation protocol]() could be performed using the [~service](https://github.com/hyperledger/aries-rfcs/tree/master/features/0056-service-decorator) decorator to convey message sending details. This change has seen a need to generalize the URL format into something that is divorce from the particular DIDComm message that is being packed inside the URL format.

@tmarkovski @swcurran @dhh1128 @TelegramSam, I'm tagging you in this issue as I know you have all done quite a bit of thinking on this issue in particular.

The motivation for pursuing a URL format for DIDComm messages is driven mainly by the need for discoverability and the need for them to be able to be invoked into an IdentityWallet via deep links.

One of the key questions that has been asked previously is whether to use a custom scheme for DIDComm messages or stick with `http/https`.

A custom scheme such as `didcomm` would be similar to how the `mailto` scheme works for email clients, the price paid by this format is if a user is sent a DIDComm message in a URL format
that is prefixed with this `didcomm` scheme, invoking the URL on a device that has no identity wallet installed, would likely lead to some confusion for the user. As nothing on the device
would recognize the scheme.

Using a scheme such as `http/https` would in contrast means, if the URL was not recognized by an installed application, the browser would invoke the URL and could redirect the user to developer
resources to download a supported mobile wallet. 

A notable limitation of registering a URL based on the 'http/https' scheme on IOS is that ownership of the domain must be proven by the app that wants to register the URL for deep link invocation.

This would prevent a generalized developer resource page being hosted.

My personal thoughts on the matter is that I think we should be opting for a custom URL scheme at the price of discoverability. Evidence of this approach can be seen in the following examples

- Email clients `mailto`
- Slack `slack`
- OpenID Connect `openid`

This resolves the issue around registering apps to invoke the custom scheme, an example of this format could be the following

`didcomm://?m=<did-comm-msg-b64URLsafe>`

Another point of conversation related to this topic has been around the need to constrain the information in DIDComm messages sent using this format to ensure, the URL is still of a size
that can be encoded into a QR-Code and reliably scanned.

I would like to surface the idea of using a redirect parameter to load the contents of the DID Comm message, similar to how it is being suggested in the DIF interop [project](https://github.com/decentralized-identity/papers/blob/master/did-authn/siop/did-authn-siop-profile.md#generate-siop-request)

`didcomm://?r_uri="https://example.com/message/12345"`

The behaviour would mean a supporting application that recieved this URL, would invoke an `HTTP GET` on the url given via the `r_uri` query parameter.

I am not un-aware of the unresolved questions in reference to user privacy and the potential attack vectors, but I remain un-convinced that there is a better solution 
and that counter measures could not make this approach sufficiently safe. I also know that this option means the format would not always be offline capable where by a QR code is used as the transport medium.

**Comment by dhh1128** [comment]
@tplooker , I agree with a lot of your thinking here. Very good stuff.

However, I think we should separate it into two separate subtopics:

1. A DIDComm URI scheme.
2. Sending QR codes for invitations to exchange DIDs.

These are related, but not identical, topics.

I would say, wholeheartedly, YES to creating a DIDComm URI scheme--and I think mailto is a great analog. I looked up the mailto RFC not long ago. We should have an equivalent one for didcomm. Basically, this converts URIs into a transport.

I think we *could* send invitations using didcomm://. However, I don't think we should *assume* that. I think sending invitations to total strangers is more likely to happen over https, with didcomm:// being used only when we know the other party has an agent. Think of the analog with email: yes, we can exchange mailto: URIs, but we also send our email addresses over http, on pieces of paper, on business cards, on QR codes, etc. The conclusion I draw is that A) we should invent didcomm://; B) it should be possible to send an invitation that way; C) it should also be possible to send invitations other ways.

For me, "discoverability" isn't that important. What I care about, far more, is virality. I want it to be possible to invite someone to connect without any preconditions about what software they already have. That means deep links, and that means https. So I'm thinking most invitations will probably be http-based. But if we're talking about the introduce protocol, where the introducer knows that the introducees already have agents because pairwise relationships with the introducer already exists, then a didcomm-based invitation makes perfect sense.

**Comment by tplooker** [comment]
@dhh1128, agree with the distinction, QR-Codes are only but one of the ways a DIDComm message can be communicated. However I do want to clarify a couple of things.

1. In regards to your point about sometimes using https:// are you meaning we will have two valid URL formats, one with a https:// scheme and the other with a didcomm:// scheme?
2. In particular, with regard to QR Codes can we safely assume that any QR-Code that contains a DIDComm message should first decode to a URL that embedded the message via a query parameter (like the above example) or a reference to the message (like the redirect example above.

**Comment by dhh1128** [comment]
Re #1: Not exactly. I don't think the https:// format needs to be general-purpose. I think it can be limited to the very special case where you need to be able to send a deep link, because you don't know whether the recipient supports DIDComm or not. And I think the purpose of such deep links could be constrained to just initiating DID exchange. I wouldn't use it for ephemeral communication or general-purpose DIDComm; it feels like too much to expect deep links for arbitrary DIDComm. (I could be talked out of that view; it's just what I'm thinking without serious study.)

Re #2: at first glance this sounds reasonable to me, but I want to ponder it more.

**Comment by OR13** [comment]
Linking some DIF related topics.

https://github.com/decentralized-identity/papers/issues/19

https://github.com/decentralized-identity/well-known/tree/master/did-configuration

I'd love to see an auth solution for DIDs that worked with `https:` first. The mobile wallet stuff seems like a special case of a URI challenge response protocol, I've raised the same point in the DIF.

I think OIDC SIOP can be seen as a DIDComm protocol, assuming DIDComm supports creating JWTs signed by DIDs, URIs and OIDC.

There will likely be many different ways to handle DIDAuth. I think we should try and support OIDC, before implementing more custom solutions, if the id_token format defined in the SIOP spec is useful.

It seems based on initial feedback from @swcurran, that SIOP id_token would work for auth, but not credentials exchange.

https://github.com/decentralized-identity/interop-project/issues/9

Can someone link an example id_token that has the format desired? I'm particually interested in what form the embedded VC are expected to be in if they are not OIDC Distributed or Aggregated Claims.

**Comment by tplooker** [comment]
@OR13, thanks. Can you clarify what you mean about an https based auth solution. What this issue is attempting to pin down, is what the url format for didcomm messages should be in general. The didcomm message that may be embedded inside the url could be an auth request or a credential offer, or any of the other messages defined in the protocols supported. 

Your comment on SIOP being a DIDComm protocol I definately agree with, with DIDComm provided we have community support, we could define a two message protocol that achieves the auth challenge request and response messages that SIOP essentially performs.

In regards to your last point I think If we start trying to use SIOP OIDC for more than just a request response auth challenge pattern i.e credentials exchange it could be a mistake. Credential exchange can be quite interactive depending if prerequisite information is required and hence does not conform too well to a request response pattern that SIOP OIDC implies.

In regards to your last point on the ID token format, in didcomms credential presentations look different to oidc identity tokens so I'm not sure I can draw a comparison there?

For completeness of the conversation check out the work below we are doing with BCGov that is essentially verifiable credential authentication using oidc, note this is a little different to how did authn is intended to work because we assume the RP wants to remain largely untouched.

https://github.com/bcgov/vc-authn-oidc

**Comment by tplooker** [comment]
@dhh18 and any others interested, shall I make an RFC that attempts to convey this if it is not too controversial? I am currently on holiday until the 18th, following that I am happy to write it.

**Comment by dhh1128** [comment]
@OR13 Thanks so much for commenting here. I have some thoughts about decentralized-identity/papers#19 that you linked here, but I'll go over there to leave them.

+1 to @tplooker writing an RFC about DIDComm message URL format. However, I'd actually call it a "transport" rather than a "format". QR codes are a transport, and so is the copy/paste buffer that we use to move around URIs...

**Comment by tplooker** [comment]
Agree with the above distinction I will attempt to draft an RFC operating along those lines

**Comment by dhh1128** [comment]
Update: I'm posting a cross-link to my comments on the DIF ticket, just so they're easily findable here. https://github.com/decentralized-identity/interop-project/issues/9#issuecomment-519728978

**Comment by OR13** [comment]
Sorry for being so late to respond.

I don't think OIDC SIOP can be used for anything other than an id_token with a `"sub": "did:example:123"`, but obviously any api that will accept an id_token can be used for credential exchange / regular api activities.

By https auth solution i mean that 2 web servers with the ability to sign with a key linked to a DID can complete an authentication flow.

For example, here is neeham schroeder with DIDs: https://github.com/decentralized-identity/github-did/blob/master/packages/lib/src/v2/didAuth/needham-schroeder/__tests__/needham-schroeder.spec.js

This is the mutual auth protocol used in kerberos.

What i've done here is not standard, but since its just a series of messages, it can be used over any channel.

If these where DIDComm messages (and they very easily could be), then this could be a solution to mutual auth over http, if the DIDComm messages where exchanges via http.

I think its helpful for us to get a concrete implementation / demo in http before attempting to generalize.

**Comment by tplooker** [comment]
Update on this issue, I have not forgotten about creating an RFC for this, discussions with neighboring communities such as DIF have lead me to try and explore something that is also acceptable there, hence this issue is taking longer to resolve.

**Comment by TelegramSam** [comment]
There was some discussion at IIW that included both SpacemanID and Tomislav. They were going to write up an RFC.

**Comment by TelegramSam** [comment]
RFC: https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0268-unified-didcomm-agent-deeplinking/README.md

**Comment by TelegramSam** [comment]
Closed per conversation in 2019-12-18 Aries WG Call.
