### ISSUE TITLE
RFC0037: missing "Presentation Reject" message

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#172]
Please describe the "Presentation Reject" message present in the choreography diagram of `present-proof` - there is no mention of it in the text.

Is this just the `problem-report` message?

Note: you can view the diagram in PR #171

**Comment by swcurran** [comment]
I think that is a Problem Report message, and so maybe the diagram needs to be clarified, rather than adding a text to the RFC?  On the other hand, the contextual use of the Problem Report is probably needed.

@dhh1128 @TelegramSam - what are your thoughts about the need for RFCs to describe how they use the `ack` and `problem report` messages in the context of a specific protocol?  Hmm...is that covered in the `protocol` RFC?  I'll have to look...it doesn't.

**Comment by dhh1128** [comment]
It is covered here: https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0003-protocols/template.md#adopted-messages

Adding a note in the protocol about the formal adoption of `problem-report` and `ack`, and about exactly where and how they are used, is totally appropriate.

**Comment by kdenhartog** [comment]
PR #188 (and the follow up PR) appears to address this problem. If you feel it satisfies the needs @llorllale please close this issue.

**Comment by llorllale** [comment]
I now understand what "Presentation Reject" means although
