### ISSUE TITLE
Q: Why doesn't didexchange/1.0/request include ~thread ?

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#208]
The did-exchange RFC does not include the `~thread` decorator on the [`Exchange Request`](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange#1-exchange-request). I think it should if it is a response to an `invitation`. `~thread` is the standard way to correlate different messages exchanged in a given *context*. 

Having this odd quirk in the did-exchange protocol then requires this particular state machine to have extra reliance on cryptographic primitives in our architecture. (my assumption here is that the RFC implies the agent should use the new keys included in the invitation for correlation)

Or is there a good reason why `~thread` is not included?

**Comment by swcurran** [comment]
Here's the rationale. Since the invitation is out of bound, delivered in plaintext and not delivered as a DIDComm message, it is not technically part of the DID-Exchange DIDComm protocol - it is a trigger to start the protocol in some cases.  Note that if you use a public DID as the recipient of the `exchange-request`, you do not even need an invitation. As such, since the `exchange-request` message is the first message in the protocol, it is the first message in the thread, and per DIDComm practices, it has a default thread that is not included in the message.

As well as the public DID case, @TelegramSam added a feature to the ACA-Py invitation process that allowed an invitation to be used multiple times - for example, by showing a QR code on a slide at the end of a presentation to invite the audience to connect with the presenter. In that case, the invitation cannot be used as the thread because there would be many DID-Exchange protocols kicked off.

This was discussed at some length (there wasn't a lot of controversy) and it was agreed that the invitation was not the start of the protocol, so is not the basis of the thread.

**Comment by llorllale** [comment]
> allowed an invitation to be used multiple times - for example, by showing a QR code on a slide at the end of a presentation to invite the audience to connect with the presenter. In that case, the invitation cannot be used as the thread because there would be many DID-Exchange protocols kicked off.

Understood, thanks!

Suggestion: if it is technically not part of the did-exchange RFC then consider removing it from the state transition matrix.

**Comment by dhh1128** [comment]
I partly disagree with this summary that led to this ticket being resolved. I hadn't seen it, and I wasn't aware of it ever being discussed in community calls. I guess I missed them.

I do agree that it's better to think about the invitation as a trigger rather than a full-blown member of the DID exchange protocol, since it is unencrypted and out-of-band.

However, any message that has an `id` can, by definition, be referenced in thread semantics. No special hookup or work is required; this is just an inherent property. We depend on this behavior when sending `problem-report` messages; any given `problem-report` can reference the message that triggered it as the start of a new sub-thread inside the relevant protocol.

So, how do I resolve the apparent contradiction that `id` on an invitation isn't part of the thread of a subsequent DID exchange--yet any `id` can be referenced, by definition? And how do I resolve the problem that an invitation can be reused?

The `id` in an invitation should become `~thread.pthid`, NOT, `~thread.thid`, in the following request. A parent thread can have many child threads, each of which has a unique `id` of its own (that resolves the duplication problem). An invitation that doesn't have an `id` doesn't create any problem, since `~thread.pthid` is totally optional. And from the perspective of an inviter that issues a blanket invitation, all of the invitations are part of a common activity--whereas from the perspective of each party that sends a request as a result of the invitation, it's a different workflow.

**Comment by llorllale** [comment]
@dhh1128 sounds good to me. Does the `connection` protocol also support this?

@swcurran @TelegramSam @dbluhm do you guys agree with this solution?

**Comment by dbluhm** [comment]
I like Daniel's reasoning and it sounds pretty agreeable to me. I think some text on why pthid is used versus thid in the RFC(s) would be good

**Comment by TelegramSam** [comment]
I agree with the Daniels.
