### ISSUE TITLE
Implementors - plan to switch from "Connections" to "DID-Exchange"? And why use DID-Exchange at all?

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#214]
This issue raises two questions about the new "DID-Exchange" name for the protocol used to establish a connection between agents.

We're interested in knowing when those implementors that have had an Aries agent since the Provo Connect-a-thon are going to be switching from using the "connection" protocol to "did-exchange"? We've decided it's too complicated in ACA-Py to support both, so we're getting ready to just switch over to support more recently created agents that use "DID-Exchange".  We have the IIW Demo that we are still using (and it's important!) and would like to continue to work, so we're wondering what StreetCred is planning @tmarkovski.  Likewise MattrGlobal @tplooker.  Any others?  Our plan is to leave the servers for the IIW Demo using older ACA-Py implementations that support "connection", and when StreetCred updates, we'll update those servers at the same time.

I also note the use of "connection" in our code for the connection object, likewise in aries-staticagent-python (@TelegramSam @dbluhm) and in the aries-framework-dotnet.  Should we really rename to "did-exchange" the thing that creates the connection object that defines the relationship between entities. Connections are about a lot more than DIDs.  My vote would be to revert the change back to "connection" drop "did-exchange" entirely. I believe that other than the name, the protocols are identical.

Anyone else want to go back to "connection", or do we just continue with the new term?

**Comment by dhh1128** [comment]
The protocol is about DID exchange. The noun that results from the protocol is a connection. I don't feel any need to change existing nouns in our code or interfaces away from "connection", or to change the name of the protocol to anything other than "DID exchange".

**Comment by dhh1128** [comment]
>the protocol is about creating and maintaining a connection

I thought it was only about creating. If we want to tear down a connection, how do we do that? If we want to tell the other party that we've updated our DID doc, how do we do that? If we want to add another party to the current 2-party connection, how do we do that? If we want to set policy for our connection, how do we do that? If we want to ask the other party what they think about our connection, how do we do that?

> It's just that we can't easily have both in one implementation

I worry a bit about architecture if we can't easily handle name changes or synonyms for a protocol. Going forward, it's at least going to need to be possible to support multiple versions of the same thing. But maybe multiple versions of one name and multiple names are separate issues?

**Comment by swcurran** [comment]
My thought is all of those things will be added to this protocol. I don't see a need to add a new protocol, but to extend this one.  All the better for it to be connections.  Do you think all of those functions need to be different protocols?

I agree that this is not great that the protocol can't be synonymed, but if you think through what this protocol does, you'll likely understand why.  We were able to parallel credential exchange protocols, but since this one is core to the agent itself (vs. on top of the agent) it is difficult.

**Comment by dhh1128** [comment]
>Do you think all of those functions need to be different protocols?

That was my assumption. But maybe it's a bad assumption. This probably needs further discussion.

The reason I thought this is that the state management for each of these problems is potentially different (e.g., I may have a different error path if I can't successfully tear down/delete a connection than I do if I can't modify the policy of a current one). Also, I thought that these operations might be versioned independently.

Now that I think about it more carefully, maybe there are ways to make my assumption less constraining...

**Comment by dbluhm** [comment]
My thinking has also been that a DID Exchange results in a connection and that a name change of the protocol does not necessitate the renaming of objects in code such as `StaticConnection` in the static agent library. I personally like the descriptiveness of "DID exchange" as that is ultimately what is happening; though it doesn't cover all the details (how could it?), I think it's at least as descriptive as a name like "Diffie-Hellman Exchange." That being said, I'm not totally opposed to another name.

I think the initial establishment of a connection is nuanced enough and sufficiently complex that keeping establishment separate from maintenance feels like a good separation of concerns.

As per our previous discussions on protocol naming, even if we did decide to combine establishment and maintenance into a single protocol, I think "connections" is still ambiguous and potentially confusing. I would recommend keeping the convention that we established of verb-noun combos such as "manage-connection" or "create-connection" or something along those lines.

**Comment by swcurran** [comment]
What I'm asking for is that we don't do an unnecessary name change from `connection` to `did-exchange`.  The change is harder than planned, requires coordination amongst implementers, and the value is negligible. "did-exchange" instead of "connections" does not reduce the effort for implementers to understand what the protocol does. It is just a different, equally ambiguous word.

I would like a definitive answer ASAP as the longer we wait the more pain and confusion we inflict on others.

**Question**: Do we keep the protocol name `connections` that has been implemented in a number of code bases, or do we switch to `did-exchange`?

> My vote is to keep the protocol name `connections`.

Others please vote.

I'm not concerned in this issue about whether we add more messages to this protocol for the rest of the connection maintenance, or we create a new protocol. And I don't think the name of the protocol helps in deciding that issue.

**Comment by dhh1128** [comment]
Stephen, I agree that the value of the new name's clarity is not huge. I think it's more than negligible, but the difference in magnitude isn't worth quibbling about.

I also agree that name changes should not be done without some deliberation.

In this case, I am inclined to keep the name not because of magnitude, but because I thought we had talked publicly about a general naming strategy and decided that "connections" was a poster child of ambiguity, and that we'd agree to use something better going forward. [Here](https://docs.google.com/presentation/d/11UVwJ2xqMmXyXr2BVsjz53S-tbMUhD1tmkhzfN7KMRw/edit#slide=id.g5b1be5d0c1_0_66) are the slides we used to discuss this on a community call. I believe it was this community conversation that motivated the change to "DID Exchange."

I don't want to come across as unsympathetic, but I'm genuinely puzzled by the "pain and confusion we inflict" comment. How is the string constant that identifies a protocol anything other than a minor detail, declared in one place in code? And why could we not declare in code that string constant A and string constant B are synonyms -- thus allowing a codebase to support both constants at the same time? I would buy the claim that codebases shouldn't generally be oriented towards supporting synonyms, but it certainly *must* be the case that robust, permanent-use codebases are written to support multiple versions of a protocol, so a multimap behavior must be implemented regardless.

Based on your articulate pushback, and respecting the heavy investment you and your team have made in protocol support, I'm imagining that there's some characteristic of routing a protocol to a handler in code that's more complex than I've understood. I'd really like to know what that is, since it sounds significant. If we can clarify what it is that makes this so hard, and it is as compelling as you imply, then I will cheerfully vote to revert the protocol name. But in the meantime, all I have to go on is my own intuition that this ought to be a 10-min change, and that if it's not, it's the codebase that ought to be refactored to make it so, not the spec. So that's a provisional vote to keep the name "DID Exchange", pending revelations of a deep issue we're not understanding.

**Comment by tmarkovski** [comment]
My initial feeling is to keep the name as it is, since renaming doesn't bring any immediate (functional) value, though I don't have strong opinion one way or the other. While the renaming for most implementors may be a few minutes of work, there are services in production that will immediately break, which are not as easily updated. If we updated this in the Streetcred mobile app, it would certainly break a number of services that rely on it.
If everyone feels strong about renaming to did-exchange, I suggest introducing a rolling update with backwards compatibility wherever possible, with a broader implementation done during one of the next connect-a-thons, which is where most codebases get heavily updated and synced.

**Comment by dhh1128** [comment]
Ah. @swcurran, is the pain you are talking about the pain of updating production deployments? That would make a lot of sense to me; I was only focused on the coding cost when I claimed this should be easy.

If there are production deployments that we don't want to disrupt, then I'm willing to change my vote to "revert the protocol name to 'connection'".

**Comment by swcurran** [comment]
It's a both a code issue and the existing implementations. It's the existing implementations and the fact that (per the developer, who is way smarter than me) it's a non-trivial effort to support both names for the protocol, because it's so core to the agent.  Supporting both credential exchange protocols was relatively straight forward and we've done that. It's because this one is about connections.

**Comment by troyronda** [comment]
Just thought I would supply a concrete version of a rolling upgrade method.

Step 1) Add support for accepting the new protocol type string (in addition to the connections one). This string acts as a synonym for the connections one. Implementations keep their other existing behaviours at this point.
Step 2) After X months, implementations begin sending the new type string.
Step 3) After Y months, implementations cease support for the old type string.

For API surface (where needed): add synonyms for new names and deprecate old ones. After Z months, cease support for deprecated names.

(this method doesn’t support both at once, but allows for a graceful transition.)

**Comment by swcurran** [comment]
Yes, that's the plan generally, and we did that for credential exchange.
The problem (per the devs) is this particular protocol. It's more work than
just a synonym. And there is literally nothing to the change than the name.

**Comment by smithbk** [comment]
At the risk of muddying the water more, there were other differences from the connectathon version of the connection protocol and RFC 23.   In particular, the body of the request has two name changes: in the 'connection' section, changed 'DID' to 'did' and 'DIDDoc' to 'did_doc'.

**Comment by swcurran** [comment]
Thanks @smithbk - agreed, as your testing found.  Sigh.

**Comment by swcurran** [comment]
We (ACA-Py team/BC Gov) are going to give up fighting against this change. We'll make the conversion to the new protocol the week after IIW and update/redeploy all instances (that we can find) of ACA-Py at that point.  We understand that StreetCred is going to do the same with `aries-framework-dotnet` the same week.

Let's not do this again.  Breaking changes must have corresponding benefits.
