### ISSUE TITLE
RFC 31 has typos and indy-isms

### ISSUE THREAD

**Issue by smithbk** [hyperledger/aries-rfcs#224]
The following messages should have a "~thread" field rather than "@thread" field:

https://github.com/hyperledger/aries-rfcs/tree/master/features/0031-discover-features#disclose-message-type

https://github.com/hyperledger/aries-rfcs/tree/master/features/0031-discover-features#sparse-responses

The URL in the catalogs field of the following message refers to an indy-hipe but I assume should refer to an aries-rfc:

https://github.com/hyperledger/aries-rfcs/tree/master/features/0031-discover-features#localization

**Comment by kdenhartog** [comment]
Would you mind making a PR for these updates?

**Comment by dhh1128** [comment]
@smithbk : ~thread is correct; @thread is wrong. (All decorators are preceded with ~; the @ prefix is only used for the two JSON-LD-isms @id and @type, as described [here](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0047-json-ld-compatibility#what-the-casual-developer-needs-to-know).) It looks like the following places need updating, instead of RFC 31:

./features/0124-did-resolution-protocol/README.md:		"@thread": { "thid": "xhqMoTXfqhvAgtYxUSfaxbSiqWke9t" },
./features/0124-did-resolution-protocol/README.md:		"@thread": { "thid": "xhqMoTXfqhvAgtYxUSfaxbSiqWke9t" },
./features/0044-didcomm-file-and-mime-types/README.md:[`@id`, `@thread`](../../concepts/0008-message-id-and-threading/README.md),
./features/0030-sync-connection/abandon-connection-protocol/README.md:"@thread": { "thid": "c17147d2-ada6-4d3c-a489-dc1e1bf778ab" }
./features/0048-trust-ping/README.md:  "@thread": { "thid": "518be002-de8e-456e-b3d5-8fe472477a86" },
./concepts/0011-decorators/README.md:  thread could send a message containing nothing but the `@thread` with one o

**Comment by dhh1128** [comment]
I believe this is now fixed in PR #230 . @smithbk Please reopen if you feel that more needs to be done.
