### ISSUE TITLE
Small Q: what is the classification for msgs like `ack` and `problem-report`?

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#234]
@dhh1128 @swcurran 

Just wondering what category do messages like `ack` and `problem-report` belong in? They are not protocols (they lack the ingredients) and they are not decorators. So what are they?

**Comment by dhh1128** [comment]
The `ack` and `problem-report` messages both implement the 1-step notification pattern for protocols, described near the second graphic [here](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0003-protocols/README.md#types-of-protocols). As such, I've been thinking of them as degenerate 1-message miniprotocols that get [adopted](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0003-protocols/template.md#adopted-messages) into a larger context.

Since 1-message protocols are so degenerate, however, you could just think of them as reusable messages that get more specific semantics when they are adopted into a particular host protocol (like ACK getting used at the end of introduce).

**Comment by kdenhartog** [comment]
I see a PR was merged that referenced this issue. Is this ready to be closed? @llorllale

**Comment by llorllale** [comment]
@kdenhartog that PR is from the aries-framework-go project :)

I left this issue open to let the question simmer in my head but after all this time I *still* haven't come up with a good *name* for these.

Thanks anyway

**Comment by kdenhartog** [comment]
Ahh, in that case, I think it's fine to keep this open. I'm just trying to clean up issues that have been resolved, but not close.
