### ISSUE TITLE
How do public DIDs work with cross-domain messaging?

### ISSUE THREAD

**Issue by jmandel** [hyperledger/aries-rfcs#239]
https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0094-cross-domain-messaging/README.md indicates that:

> The Receiver of the message knows from the "to" field the DID to which the message was sent. From that, the Receiver is expected to be able to determine the DID of the Sender

I think this implies that the receiver must be using a pairwise DID -- because if the receiver used a public DID, that receiver DID couldn't uniquely identify the sender. However, the Assumptions section states:

> The Receiver's DID MAY be a public or pairwise DID

These two claims seem incompatible. (Or I'm confused, which is entirely possible -- I tried asking about this at https://chat.hyperledger.org/channel/aries?msg=YagCRBFfQedggsqjm but didn't get a response, so figured a GH issue may be a better fit.)

**Comment by llorllale** [comment]
Pinging @swcurran (the author)

**Comment by swcurran** [comment]
@andrewwhitehead, @tplooker - can the two of you discuss this at IIW with others there? This has come up for discussion a couple of times and has not been resolved. Last it was talked about (perhaps 2 months ago on an Aries call), it was left unresolved. AFAIK current implementations are only using public DIDs during DID-Exchange, not after connection establishment.

I believe at one point (way, way back) we talked about allowing a "from" in the "forward" as a potential mechanism for this. That would give another mechanism for a unique connection to be identified.

**Comment by dhh1128** [comment]
I believe the reason this topic died down is because the implementation of the encryption envelope reveals the recipient (on the final leg of the route). For sure it reveals the recipient's public key (which can be used to lookup the DID); more recently, I have heard people advocate that it should also or instead reveal a DID key reference. Either way, there is no ambiguity, unless you are not encrypting.

But that's only about a 80% confident answer.

**Comment by jmandel** [comment]
I may not be understanding your comment @dhh1128, but when you say "Either way, there is no ambiguity", do you mean "no ambiguity about the identity of the sender"? If so, could I ask you to spell out for me the algorithm that the recipient follows to learn the sender's DID? (I'm totally new to this world, so I'm very possibly missing something basic.)

**Comment by llorllale** [comment]
@jmandel one of the implications of what Daniel is saying is that the `to` field may actually be redundant due to the way the [encryption envelope](https://github.com/hyperledger/aries-rfcs/tree/master/features/0019-encryption-envelope/README.md) reveals the public keys of the recipient of the message.

**Comment by swcurran** [comment]
The issue is less about public DIDs per se, but rather about an entity sharing one DID across multiple relationships. As I understand it, reducing the number of keys for an enterprise to manage would be a benefit, so using shared DIDs (public or pairwise would presumably be fine, although having it a public DID would be easier to rotate) for many connections would be an approach to consider.

The statement in the RFC is technically correct, as long as one DID is used per connection. But I think it is getting the shared DID use case to work that is the concern in this issue.

Is that correct @jmandel?  Any thoughts @dhh1128 @tplooker?

**Comment by dhh1128** [comment]
Let's start with the easy part. The receiver knows which DID is the intended recipient, out of all the DIDs it owns, because of what I said in the previous comment. Does that part make sense?

Now, if this is a pairwise DID, obviously the sender can also be deduced. But if I understand your question correctly, you're asking about the case where the *recipient*, NOT necessarily the sender, has a public DID. Right?

The algorithm you're asking about starts with the realization that the public key of the sender is known to the recipient. This *must* be true for the crypto to work.

Now, the question is, what can the recipient deduce from the value of the sender's public key?

If the sender is using a private DID that the recipient knows (pairwise), then the recipient can get the sender's DID by doing a reverse lookup on the public key ("what DID do I know that uses this public key?") I believe the indy-sdk wallet module supports this type of lookup.

If the sender is using a public DID, OR if the sender is not using DIDs at all, OR if the sender is using a private DID that the recipient doesn't know, then the recipient can't map from the sender's public key to anything useful. However, the sender CAN recognize repeated messages from the same sender.

If the sender is using anonycrypt mode, then each transmission from the sender uses an ephemeral public key, and the recipient can't recognize multiple transmissions from the same source.

**Comment by jmandel** [comment]
@swcurran 
> rather about an entity sharing one DID across multiple relationships 
>  I think it is getting the shared DID use case to work that is the concern in this issue.

That's correct. (Though it's also worth saying that one *key* can technically be used across multiple DIDs, so the issue of "reducing the number of keys" isn't strictly tied to the number of DIDs issued. It's really about which identities can be correlated, and by whom, and at what point in the interaction.)

@dhh1128 

> But if I understand your question correctly, you're asking about the case where the recipient, NOT necessarily the sender, has a public DID. Right?

That's exactly what I'm wondering about, yes. 

> The algorithm you're asking about starts with the realization that the public key of the sender is known to the recipient. This must be true for the crypto to work.

Okay, and this public key is embedded in the message somewhere by `[pack](https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/README.md#packmessage--wh-message-receiverkeys-sendervk----jwe)`, at "protected -> recipients -> header -> sender"? I think this is the (simple / obvious) piece I was missing. 

Thanks so much for the follow-up and patient explanation! Given my current understanding, I might suggest updating the paragraph that starts with "The bullet above about the unpack() function returning the signer's public key deserves some additional attention..." to something like:

> The recipient of a message must keep track of the specific key used by the sender to AuthCrypt this message, so that the recipient can, for example, use that key in responding to the arriving Message. This verification key is returned by as `sender_verkey` by `[unpack()](https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/README.md#unpackmessage--wh-jwe----res)`.

**Comment by tplooker** [comment]
This issue is dependent on a resolution to #104. We will leave this issue open until a concrete solution is proposed and then reassess its implications.

**Comment by TelegramSam** [comment]
Continue Issue here: https://github.com/decentralized-identity/didcomm-messaging/issues/24
