### ISSUE TITLE
0049-repudiation - using asymmetric encryption is vulnerable to QC

### ISSUE THREAD

**Issue by sidhujag** [hyperledger/aries-rfcs#251]
https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0049-repudiation/README.md

JFYI, using asymmetric encryption is the weakest link when accounting for Quantum resistance, and this is the first form of encryption to go. This should be a drawback as highlighted. Perhaps using Digital Signatures can work if you sign a hash of the message as the sender or come up with a symmetric key signed by both parties separately using a difference nonce.

**Comment by kdenhartog** [comment]
@mikelodder7 would you mind taking a look at this one and providing a response?

**Comment by mikelodder7** [comment]
Sure asymmetric crypto will be the first to go once there is a viable QC that can implement Shor's algorithm. How far away is that? No one knows except that the more we get into QC, the more we realize how hard it is and it will be to implement a crypto algorithm on them. 
Signing a hash will not protect you from QC. That's what digital signatures do today. RSA-OAEP, ECDSA or EdDSA. They all do it. The whole point of the signature is only the private key owner should have been able to produce it, no matter what is signed, hash or not. If QC eventually becomes a reality, then we don't have this guarantee because anyone could have produced a valid signature under these schemes. 

Symmetric crypto doesn't save you either if you want non-repudiation. The whole point is that more than one party knows the secret. Usually, it's just two, Alice and Bob. Alice knows only Bob could have HMAC'd the message because he's the only other participant that knows secret **K**. But Alice can't show prove it to anyone else because Alice or Bob could have generated the HMAC signature. 

So, for now, I think this system is fine as is. What should be considered is does this RFC allows for any signature scheme including PQCrypto. If so, then we're good and we just need to decide which ones should be implemented like CRYSTALS or Lamport hash sigs.

I don’t think QC is going to be realized for at least another 10 years and even if it does, there are certain algorithms that need to be implemented before worrying about current cryptography being broken.

I'm more concerned with the key management aspects of the agents having sloppy or poorly designed security such that keys are stolen. Just my two cents.

**Comment by sidhujag** [comment]
Grover's algorithm can break symmetric encryption but if you use sufficiently large enough keys symmetric is already quantum safe.

I guess if you don't have a private line of communication then no point anyway.

Just thinking out loud if you had a shared secret, you can simply sign a message (the payload hash) authenticating the sender and include next to the payload (message). Encrypting it all via shared symmetric key. But if no secure context is established then you lose ability to communicate shared secret. It's probably fine for now like you said because of key management and ease of use.

**Comment by mikelodder7** [comment]
Grover's algorithm does not break symmetric crypto. It weakens the keyspace by half, thus 128-bit encryption now is reduced to 64 bits. AES and CHACHA cannot be broken by QC. They just flip and shift bits. By using 256-bit symmetric crypto, you can claim PQ crypto. It also begs the question, "How long do you need the data secured?" In the local agent wallet, probably not very long for individuals. Only 1-5 agents will be accessing an individual's data and when QC becomes a thing, simply stop sharing the data. There are use cases where longevity is necessary like financial, gov't, academia, telco, and medical so investigating PQ crypto now makes sense. But that does not mean they cannot use existing crypto. It isn't broken and isn't likely to be within 10 years.
As long as Aries implementations allow for switching to PQ crypto implementations easily then this isn't a problem either.

The CRYSTALS and PICNIC PQ crypto suites are two I'm investigating right now to put into [Ursa](https://www.hyperledger.org/projects/ursa). Its my understanding that Aries plans to be compatible with Ursa. Hope that helps.

**Comment by sidhujag** [comment]
Thanks mike that makes sense. We are planning on building out using Aries. Do you know what sort of work is involved in making it compatible. Perhaps I can help.
