### ISSUE TITLE
RFC 250: Should rich schemas be decoupled from anonymous credential?

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-rfcs#253]
From https://github.com/hyperledger/aries-rfcs/pull/250#discussion_r333710229

I am curious about the linking between https://w3c.github.io/vc-data-model/#zero-knowledge-proofs and this RFC?

I'm also wondering if the anonymous credential material (e.g., link secrets) should be decoupled from the rich schema material?

Somehow there seems to be three topics in my mind.
* Support for W3C Verifiable Credentials (but not limited to ZKP, of course).
* An (extension?) for link secrets: anonymous credentials.
* Rich schema concept / discussion.

**Comment by kdenhartog** [comment]
The PR that fixed this was included in the status change. If it's not satisfactory then we should revert the status. I assume this was good because there wasn't a response to the rocketchat, this issue, or the PR. I'm going to go ahead and close this issue. If the discussion is ongoing please let me know and I can help revert the status.
