### ISSUE TITLE
Maximum value of delay_milli

### ISSUE THREAD

**Issue by lovesh** [hyperledger/aries-rfcs#258]
In [RFC 32 on timing decorators](https://github.com/hyperledger/aries-rfcs/blob/master/features/0032-message-timing/README.md), there is no upper limit defined on `delay_milli` so a sender might be able to a DoS attack by setting a large `delay_milli`. Do we expect every implementation to set its own limit and send an error back when this limit is exceeded or should the RFC set a max limit?

**Comment by kdenhartog** [comment]
This is a tough one. I think it's useful to set an upper limit for the problems you described, but it's possible for implementations to stick these delayed messages in a delayed queue to account for the temporal correlation as is highlighted in the RFC.

I'm not overly opinionated on this, but I do think that we shouldn't set it too small (e.g. less than a minute) so that we can properly account for timing correlations. Would something like 10 minutes seem reasonable to you?

@dhh1128 what's your take on this?

**Comment by dhh1128** [comment]
I'd say we should recommend an upper limit (maybe 600 seconds = 600000 millis = 10 min). However, we should probably revisit more carefully when we write an RFC about how to use DIDComm with mix networks.

**Comment by dhh1128** [comment]
Fixed in PR #279
