### ISSUE TITLE
RFC 0023: minify connection invitation?

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-rfcs#261]
Connection invitations are often going to be represented as QR codes. Having them be as short as possible would decrease the visual bandwidth we need. This is not just a nice-to-have; it may have a significant effect on whether an invitation is usable with particular software or cameras. Evernym's internal testing is running up against QR size limits that we don't like, based on the current message's information density.

I'm wondering if we could agree on some or all of the following conventions to reduce pressure on QR code size:

* Minify key names like "serviceEndpoints" and "recipientKeys" and "routingKeys" to "se", "rek", "rok"
* Minify `@type`'s value to something like "didex/1.0/inv"
* Strongly suggest that service endpoint values be as short as possible

(Both of the minifications would apply only to connection invitations, not to all DIDComm message types, and would have to have reverse mappings to their full forms declared in the RFC. This feels yucky, but it is true that this one message has unique requirements...)

An obvious alternative is to make the QR code a short link that redirects to a longer link containing expanded data. The problem with this is that it requires the URL to be followed, whereas we were trying to make it possible for DIDComm-aware software to pick apart the URI/QR code, parse out the underlying DIDComm invitation message, and act on it, all without involving the HTTP stack.

**Comment by llorllale** [comment]
> QR size limits that we don't like

What limits are you guys running into, and how much would this proposal improve things?

**Comment by dhh1128** [comment]
@khagesh or @tylerquinnton, can you comment on the size issues that led us to experiment with minimizing?

As far as how much it will help, I would say this may reduce size of the invitation by 25-50%. That could provide some genuine benefit, but it's not a panacea.

**Comment by tylerqr** [comment]
@dhh1128, older phones can't scan a QR code that has the entire connection invitation in it. The QR code is just too big. I'm hoping to make the QR code a simple short link that tells the phone where to go download the connection invitation, as you have indicated.

**Comment by khagesh** [comment]
@dhh1128 @llorllale There are two technical problems that we are facing with large data in QR codes.

1. QR Codes have a maximum capacity. Here is what it looks like as of now
| QR Code Data Capacity |
| --- | --- |
| Numeric Only |  Max. 7089 characters |
| Alphanumeric | Max. 4296 characters |
| Binary (8 Bits) | Max. 2953 characters |
So, if invitation QR code has details about sender and extra text or if we increase size of metadata that needs to be sent in invitation, then we can hit max limit easily. Since we can't trim down invitation details because they are necessary, we can at least shorten key names to stay below max limit.
2. Bigger QR codes are slow to scan on lower end devices. Some devices such as Nokia 1 and some old HTC devices takes lot longer to scan bigger QR codes.

As both Daniel and Tyler suggested that one option is to use short link, and that link is converted to QR code instead of whole invitation details. But, this option has it's own pros and cons.

**Comment by llorllale** [comment]
@dhh1128 I think it makes more sense to categorize this as a problem of *delivery*/*transport* of the invitation, not the invitation itself. This is the direction we were heading in in #146 anyways. Not sure what's happening with the RFC though...

Even if we minify as you say, it won't be enough to offset the extra characters in this invitation:

```jsonrc
{
    "@type": "didex/1.0/inv",
    "@id": "12345678900987654321",
    "label": "Alice",
    "rek": ["8HH5gYEeNc3z7PYXmd54d4x6qAfCNrqQqEB3nS7Zfu7K"],
    "se": "https://example.com/endpoint",
    "rok": ["8HH5gYEeNc3z7PYXmd54d4x6qAfCNrqQqEB3nS7Zfu7K", "IdmVWWBQMr5U17nhiVLk8VqSlcOw0XkXypnC5qJR7Sd", "TFJ2lxI4GfyaPrhcic49ComTg3TCGbGmFzkQtcJyx8R"]
}
```

To solve this generically I think the Inviter should QR-encode a `didcomm` URL where the invitation can be fetched.

**Comment by dhh1128** [comment]
Okay. I wanted to open the issue so the question could be publicly asked
and answered, but I am okay if the community wisdom is that minifying is
not worth doing.

**Comment by llorllale** [comment]
@dhh1128 

> I wanted to open the issue so the question could be publicly asked
and answered, but I am okay if the community wisdom is that minifying is
not worth doing.

To be clear - I speak for myself, not the community! You may keep this issue open and collect more feedback. You can raise the issue on the weekly call as well.
