### ISSUE TITLE
RFC 289 as a community introduction (neutrality)

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-rfcs#292]
It has been proposed that [RFC 289](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0289-toip-stack) become a conceptual overview of the Aries community. There is a lot of good content in this document that would be useful for such a purpose. However, I'd like to understand better how we can ensure this RFC is neutral (not favouring) certain credential types and certain governance structures.

I believe it is important that we continue to develop a neutral communications protocol and allow for flavours of credentials and governance structures. This communications protocol should also extend beyond "just identity" cases. This neutrality is even more important when we begin thinking of certain RFCs as a community overview.

Examples:
- "ZKP-based credentials are particularly important to the ToIP stack" (sandwiched in a larger list of credential types). The principle of selective disclosure might be its own topic.
- Layer 1: Ledger-based cryptographic accumulators is an example of a credential revocation mechanism and agent authorizations. Some ecosystems and/or ledgers might not support cryptographic accumulators and may offer alternatives.
- I think Figure 5 is showing an example for a person's physical credential analogues. Of course, there can be other scenarios for DIDComm.
- Roles in the Governance Stack
  - Table 1 is being positioned as "the roles" rather than an example. I was also trying to think about how many of these roles were needed for a community introduction (to DIDComm). Maybe there should be links to other documents to reduce confusion.
  - Governance roles discusses "permissioned network".

Other questions:
- Under Hub, was there special meaning to "It is controlled exclusively by the DID subject". Is an example of control the idea that the DID subject encrypts their data prior to storage? (and that storage could be a cloud service).
- "Migrate and port ToIP data". The term ToIP data wasn't quite defined - there is probably a discussion on the scope of portability.
- Figure 5. 
  - I was going to comment that there are potentially extended versions of this diagram. Is this the reason for the word "basic"?

**Comment by dhh1128** [comment]
Tagging @talltree and @vinomaster and @darrellodonnell to make sure they see @troyronda 's excellent comments above.

**Comment by mac-arrap** [comment]
+1 on the questions about governance. That seems very specific

**Comment by jljordan42** [comment]
For sure the concepts in the dual stack should allow for diversity (is that the right word?) in implementations of both sides of the stack. I think context will matter quite a bit as different trust communities arise and necessarily interact. 

For example, a person as a citizen receiving their identity attributes from a government issuer and using them to provide proofs in the context of receiving personal services should have certain rights that support their personal agency and privacy. 

When that same person is authorizing a gas pump, owned by a legal entity they are authorized to represent, to emit data to a government regulatory service using that data to ensure that pump is dispensing a litre of petrol ... well there are a different set of governance frameworks interacting there. 

Nevertheless, the capabilities of a Trust over IP stack enabled set of devices and governance frameworks should make these scenarios possible without presenting that individual with a user experience that hinders their ability to complete these tasks with ease and confidence.

**Comment by talltree** [comment]
@troyronda Sorry it's taken me a few days to get to this due to travel. I agree with @dhh1128 that you raise a great set of questions, some of which I've already discussed with the other original authors and we're going to revise (I myself will not be able to get to it until this weekend, but others may before that).

On the governance stack, you are correct that the roles are exemplary and not prescriptive, i.e., it's the governance authorities (GAs) who decide on:

1. What layer(s) they are designing their governance framework (GF) to cover.
1. What roles to include (the goal of the ToIP stack architecture is to define a bunch of standard roles for GAs to be able to use (but they could always define others as needed).
1. What credentials are needed (if any—for example some Layer One DID networks, especially permissionless, will not involve any credentials for governance).
1. What policies should govern each of those roles and each of those credentials.

So it's really a metaframework for defining governance frameworks, not a governance framework itself. That's why it can encompass many different trust architectures and trust communities within the same overall stack.

**Comment by swcurran** [comment]
Per Aries WG Meeting 20200805 - closing -- we'll leave the number the same. Closing.
