### ISSUE TITLE
did-exchange: question regarding "Agency Endpoint"

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#296]
@dbluhm @swcurran @TelegramSam @dhh1128 

What are we referring to as an "Agency" when in the did-exchange RFC we say the following about "[Agency Endpoint](https://github.com/hyperledger/aries-rfcs/blob/master/features/0023-did-exchange/README.md#agency-endpoint)":

> The endpoint used to transmit the exchange request is either present in the invitation or available in the DID Document of a presented DID. If the endpoint is not a URI but a DID itself, that DID refers to an Agency.
> 
> In that case, the serviceEndpoint of the DID must be a URI, and the recipientKeys must contain a single key. That key is appended to the end of the list of routingKeys for processing. For more information about message forwarding and routing, see HIPE 22.

**Comment by dhh1128** [comment]
An "agency" is just a shared service endpoint--a service that fronts multiple agents. If Alice, Bob, and Carol all receive DIDComm messages at the same place, that gives them herd privacy. It also implies that there is a mediator sitting at that endpoint, consuming `forward` messages and passing their payloads on to another mediator--the cloud agent for Alice, Bob, and Carol, respectively. All messages delivered to edge agents using this type of mechanism have to be double-wrapped with a `forward`, since the "agency" peels off one layer of the onion, and the cloud agents of Alice, Bob and Carol, in their capacity as routing mediators, peel off the other layer.

**Comment by llorllale** [comment]
Thanks. Seems like we should point to the [`Agency`](https://docs.google.com/document/d/1gfIz5TT0cNp2kxGMLFXr19x1uoZsruUe_0glHst2fZ8/edit#heading=h.wnffz4kddl9) entry on the Sovrin Glossary.

However, it seems strange to have the differentiator be merely this:

> **If the endpoint is not a URI but a DID itself**, that DID refers to an Agency.

It does not necessarily follow that the subject of a DID referenced in an invitation's `serviceEndpoint` is an Agency. Iff it's a public, well known DID (probably hosted at the Agency's `.well-known` endpoint), then it's an Agency. Otherwise we have no idea (I think)

**Comment by dhh1128** [comment]
You are correct that we don't know whether a DID referenced in an invitation's `serviceEndpoint` is the DID of an agency or of some other entity that's acting as a mediator. However, whether it's an agency or not doesn't really matter--the point is that it's mediating in the same way that agencies do.

I don't mind revising the text to nuance it a bit, but I don't think it materially changes the analysis.

**Comment by llorllale** [comment]
Fair enough. Thanks
