### ISSUE TITLE
Simplify the "Ack" feature protocol and move to Accepted

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#306]
I think the simple "Ack" protocol should be moved to Accepted as that message is in some use. However in looking at the RFC, there are some more complex features in the RFC that I don't think would be considered "Accepted".

I recommend that we remove the "~please-ack" decorator and the other advanced features from the RFC, leaving just the ACK message.  The "~please-ack" decorator could go into a separate RFC if there is interest, possibly with the other related advanced features. There is not really a reason that the Ack message and the ~please-ack decorator need to be in the same RFC vs. being in separate ones with the ~please-ack decorator referencing the Ack message.

Does anyone object to that approach?

Has anyone implemented the "Ack" message?  The ~please-ack decorator?

**Comment by llorllale** [comment]
aries-framework-go implements the did-exchange protocol which itself adopts the `ack` message to notify the inviter upon successful completion of the did-exchange.

RFC0015 is not a protocol since it lacks core [ingredients](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0003-protocols/README.md#ingredients) of a protocol (roles and states). Both the messages it defines are ones up for adoption by other protocols - I'm temporarily calling these "orphaned messages".

I agree with removing `~please-ack` into a separate RFC because, as a driver of a protocol's state, the use of `ack` should be strictly defined by a protocol. I agree that `~please-ack` introduces needless complexity and ambiguity.

I also agree with moving this RFC (with just `ack`) into ACCEPTED status. This RFC by its own can't be tested with the protocol suite.

**Comment by swcurran** [comment]
This issue has been addressed with the merging of #316. The 0015-acks RFC now covers only the ACK message, and a new RFC has been added for ~please_ack.

Closing.
