### ISSUE TITLE
RFC0028: why is the `request` message not part of any state machine?

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#309]
@dhh1128 @TelegramSam @swcurran @tplooker 

This line regarding the [`request`](https://github.com/hyperledger/aries-rfcs/blob/master/features/0028-introduce/README.md#request) message was brought to my attention (emphasis mine):

> **This message is not part of any state machine**; it can be sent at any time, and when it is received, the recipient can choose whether or not to honor it in their own way, on their own schedule.

Why not? I believe that...

* When the Introducer receives a request, they may a) transition to "arranging", or b) transition to "abandoning".
* When the Introducee sends a request, they may a) transition to "deciding", or b) transition to a new state called "abandoning".

**Comment by dhh1128** [comment]
Suppose a guy walks up to you on the street, flips open his overcoat to reveal a bunch of dangling watches, and says, "Hey, Mister, want to buy a watch?" He looks shady, so you ignore him and don't even respond. Have you abandoned the watch buying protocol, or have you refused to engage in the protocol in the first place? Do you need a state machine to ignore something, or only once you pay attention?

When I wrote the RFC, I was defining "abandon" to mean that an introduction is underway, but a party decides to disengage without completing the workflow. Under that view, it doesn't make sense to equate ignoring the request with abandoning an introduction.

However, we could decide to answer my watch-buying question by saying, "At least one party--the watch salesman--thinks a protocol has begun, so interpreting the 'ignore' decision as abandonment is reasonable from his perspective." This would allow us to accept the suggestion in your first bullet point.

I think your second bullet point still doesn't work, however. The reason is that "deciding" means to decide about a proposal, and no proposal has been sent. The introducee who sends a request therefore can't transition to "deciding."

**Comment by llorllale** [comment]
> I think your second bullet point still doesn't work, however. The reason is that "deciding" means to decide about a proposal, and no proposal has been sent. The introducee who sends a request therefore can't transition to "deciding."

Right, let me amend that:

When the introducee sends a `request`, they enter a `requesting` state. When they receive a proposal, they enter the existing `deciding` state:

![introducee](http://www.plantuml.com/plantuml/png/LSyn3i8m30NGFQVmZDGBCA3U0p64-WiijKwmKr1lJoYDAAFzdxxitakqCazZk0k3CEMo4CC7armaQGZdmuMwxaI6nmmleZSwaaEvRS8k-K368FnbXW7o16LBENaSGyjM-8gohukvieeDdfCw_d6yHkMacsNeyeDRjhfwRcZ5RUwXN5zy0m00)

**Comment by dhh1128** [comment]
@llorllale I am fine with the tweak you describe, where the potential introducee goes into a `requesting` state. That makes sense to me.

Going back to the guy trying to sell a watch: I think this scenario uncovers a general issue with all protocols, which is that there is not necessarily symmetry among all participants with respect to the perspectives on state. Most (all?) protocols I can imagine begin with one participant making a first move. Before any response is made, the first mover believes a protocol is happening--but that may not be true from the other participants' perspective(s). Maybe the other participant(s) didn't even receive the message...

I'm starting to feel that the participant who receives a protocol-beginning message from somewhere has to make a decision about whether to engage, and that this decision is what determines whether the protocol is underway at all, from their perspective. If they decide to ignore the message and not engage at all, I don't think that should be modeled in their state machine. But if they engage in any way--even to send back an error saying they're not going to complete the protocol--then the state machine needs to account for it.

Applying that reasoning to this specific problem, I'd say that if a potential introducee requests an introduction, the protocol has begun for them. It begins for the potential introducer if they decide to assume the introducer role and work on the protocol, but it doesn't begin for them if they ignore it.

**Comment by llorllale** [comment]
@dhh1128 I think that's an implementation detail.

**Comment by llorllale** [comment]
Closing this as PR #313 was merged, thanks!
