### ISSUE TITLE
RFC 0032 ~timing - what to do if some fields not supported?

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#324]
We've implemented and extensively used the simple version of the `~timing` decorator, supporting the `in_time` and `out_time` parameters. We don't have a need and would prefer not to support the more complex options - `delay_milli` and `wait_until_time` as they may introduce some new agent complexity. For example, those might require adding a new persisted queue to hold delayed messages to prevent loss in case of container termination.

@dhh1128 - is it possible/appropriate to add updates to the RFC about the expected behaviour if some of the options are not supported?  Do we just carry on, ignoring the parameter?

Also, is the expected behaviour for the post `expires_time` processing of a message simply to drop the message? Would that mean deleting local persistence of the thread is expected?

**Comment by dhh1128** [comment]
My expectation when I wrote this was that anything that wasn't supported
would just be ignored. I think it's great if we add a little bit of verbage
clarifying that. If the expires handling is implemented, I think it should
be to drop the message, but not to drop the thread, because in the future
it's possible that a message would be resent to make the thread active
again.

**Comment by swcurran** [comment]
Clarifications added in #441. Will close if/when that PR is merged.
