### ISSUE TITLE
The use of DIDComm in RFC 0270 Interop Test Suite

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#335]
I think there are a couple of issues with this phrase: 

> Both channels use DIDComm over HTTP.

Reference [RFC 0270, item 2](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0270-interop-test-suite#suite-will).

This RFC overview of the Test Suite goals and requirements should be agnostic to the front channel transport. Each agent should be able to configure it's agent under test to use the transport it supports. I don't think such a requirement should be mentioned in this RFC. There are a variety of ways an agent developer can enable support for different transports.

For the backchannel, the requirement to use DIDComm unnecessarily restricts the architecture of the test suite and, depending on the architecture, could introduce more effort to build the test suite itself and for agent developers to build their backchannel.  This RFC should not be opinionated on that, but be driven by implementation.

Further, the backchannel API is likely to be significantly larger than is anticipated by the [backchannel](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0270-interop-test-suite#backchannel) section of this RFC. This same discover was made in trying to define the briefly considered "Admin Protocol". It turned out the Admin protocol grows with the number of protocols. In the test suite case, the backchannel API might (and I think it will) grow with the number of protocols. Regardless of whether that happens or not, implementation should drive such requirements, not this RFC, and as such the restriction to use DIDComm and a test suite protocol is an implementation issue.

I recommend dropping that line from the RFC and updating the Backchannel section of the RFC to reflect that.

**Comment by dhh1128** [comment]
<friendly_grin_and_shrug>I mostly disagree. I think the current language is appropriate and correct. I think the frontchannel should be HTTP only; generic adapters can be written so agents who speak another transport can be tested without modifying the test suite to know about it. I think the backchannel should be DIDComm, too, since that's the only mechanism that we can guarantee that all agents will already have support for. I don't think the backchannel API will grow significantly, if we do it right; the fact that it has, historically, feels to me like evidence of incorrect generalization. Etc.</>

However, I'm not trying to be convincing about the above assertions -- only to point out that another perspective also exists. I am willing to change the language to reflect the general consensus of the community (or approve a PR that does so). So, do we have evidence that the community truly agrees with either of us -- or is it just muddy?

**Comment by TelegramSam** [comment]
I think it's muddy, and most of us don't currently have a strong opinion. I think if we added a comment to the RFC indicating that options are being explored, that would capture the current status.

**Comment by dhh1128** [comment]
Okay, let me raise a PR that has language reflecting our ambivalence, and see if it seems reasonable to everyone.

**Comment by dhh1128** [comment]
I've raised a PR that attempts to describe the ambivalence without prejudicing the answer. How do you feel about what I'm proposing, @swcurran ? https://github.com/hyperledger/aries-rfcs/pull/426

**Comment by swcurran** [comment]
Good 'enuff!  Let's move on.
