### ISSUE TITLE
RFC 0095 Add role attribute into basicmessage

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-rfcs#416]
Although the protocol specification mentions `role` there is no `role` attribute in the message. I understand we should keep this protocol simple, but I think it's just a small addition. It would help developers of the chat app, for example, to distinguish whether it's an inbound or outbound message. Happy to make PR.

```
{
    "@id": "123456780",
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/basicmessage/1.0/message",
    "role": "sender | receiver",
    "~l10n": { "locale": "en" },
    "sent_time": "2019-01-15 18:42:01Z",
    "content": "Your hovercraft is full of eels."
}
```

**Comment by swcurran** [comment]
Not sure this makes sense.  Since this is always sent by the sender, the value would always be "Sender". 

I'm guessing you are thinking of the protocol state object set up by the sender/receiver on sending/receipt.  That object is not specified - it's up to the agents to decide on a format for that as it is internal to the implementation.

**Comment by jakubkoci** [comment]
@swcurran You're right it doesn't make sense in this way. I didn't realize it at all 😄 

However. I understand it's probably up to an agent. But what if I as a user have messages stored in one agent and want to move to a different one. Then I'm not able to do just simple export/import and keep the information about the `role`. 

Is there any idea how to approach this? Or this is something we intentionally don't want as part this RFC and it should be defined in "more advanced and full-featured message protocol" as mentioned in this RFC?

**Comment by TelegramSam** [comment]
I think it is out of scope for this protocol, as mentioned.

The concept of moving data (beyond keys, relationships, and credentials) has not been widely discussed. It does align more closely (perhaps) with some of the secure data storage work being discussed in at DIF and CCG conversations.

**Comment by swcurran** [comment]
Another angle on what you are talking about - a bit of a tangent.

We think that the agent storage should not be (automatically) used for long term state beyond the completion of the protocol.  We ran into this because of a practical issue - our agent storage (aka wallet) was getting massive, much larger than we wanted. But in thinking about it, we came to the conclusion that the agent framework should not do long term storage of interactions, and that the controller (the business logic attached to the agent framework instance) should persist data if necessary.

In your example, you want to keep a history of the messages exchanged.  We're thinking that the _controller_ should decide if and where that history should be retained. If should not automatically go into agent storage, and often (particularly for enterprise agents) it will not go there.

This does go to what it means to "export" and "import" agent storage for portability, and for backup/restore. What guarantees about data should we offer?  What options?  To put it another way, should protocol execution history be included in migration from one agent to another?

**Comment by TelegramSam** [comment]
> should protocol execution history be included in migration from one agent to another?

I think the importance of this varies substantially by protocol. 

I think we need to attempt 'core' export/import before we get to things like this.

**Comment by kdenhartog** [comment]
Looks like this issue may be answered from my understanding. Anyone care to comment/close it?

**Comment by jakubkoci** [comment]
> I think the importance of this varies substantially by protocol.

I see it in the same way.

> I think we need to attempt 'core' export/import before we get to things like this.

@TelegramSam Are there any RFCs or other documents about the export/import feature?

I agree the framework should not enforce storage mechanisms. I still see the portability issue here, but I understand it's related to the export/import area, so I'm closing this.
