### ISSUE TITLE
connection request message not including thread block

### ISSUE THREAD

**Issue by rajeshkalaria80** [hyperledger/aries-rfcs#417]
I am testing connections 1.0 protocol interoperability between various implementation.

So, when "inviter" generates an invitation and that invitation is sent to "invitee". At this point, my assumptions are:
	a) a thread id would have assigned to this interaction.
	b) "inviter" should provide/send invitation url and the thread id both to the "invitee"

When "invitee" responds with "request" message (https://github.com/hyperledger/aries-rfcs/tree/master/features/0160-connection-protocol#1-connection-request), should use provided thread id so that when "request" message arrives on "inviter"'s side, it can match appropriate interaction.

Are my assumptions wrong or have we already decided how the flow should work (meaning shall we rely on something else rather than thread id etc)?

**Comment by dhh1128** [comment]
IIRC, the invitation and the connection request are not the same thread. This is because an invitation could be sent to multiple parties (or to the public in general). Rather, the connection request should reference the invitation using ~thread.pthid (the invitation is the parent of the connection, not its same thread). See #208

**Comment by rajeshkalaria80** [comment]
ok, I understand now and it makes sense, thanks.
