### ISSUE TITLE
DIDExchange Role Names

### ISSUE THREAD

**Issue by TelegramSam** [hyperledger/aries-rfcs#457]
The roles in DID Exchange are _inviter_ and _invitee_. This made sense when the invitation was part of the protocol. Now that the invitation has been moved out to Out-of-Band Protocols, should those roles be adjusted?

**Comment by swcurran** [comment]
That's an interesting one.  My (slight) preference is to rename them, as if we were writing this from scratch, we would probably use requester and responder, but on the other hand is that a necessary change?

I was also thinking that in the case of sending a request to arbitrary public DID with a did-communication service that there was no invitation, but there really is an implied one by the existence of that service in the DIDDoc. So in think in all cases there are invitation-based roles.

So, a slight preference to change, but not a strong one.

**Comment by kdenhartog** [comment]
commenting to say I've seen this and am choosing to abstain because I have no preference.

**Comment by swcurran** [comment]
Per Aries WG Meeting 20200805 without consensus.  Only @llorllale and @swcurran spoke, so others may not care.

Since the protocol only has two messages, I think it makes sense that we use the role names related to the actors for the two messages -- "requester" and "responder".  A requester sends a request either because it received an in invitation, or because it used a public DID as an implicit invitation.

The slight disconnect there is that OOB uses "sender" and "receiver" and the "sender" in OOB will be the "responder" in DID Exchange, and "receiver" in OOB will be the "requester" in DID Exchange.  And that is OK, as that is how we have defined the message names.  This was the same in RFC 0160 Connections and when we had DID Exchange without OOB.

**Comment by swcurran** [comment]
PR submitted to address this #526

**Comment by TimoGlastra** [comment]
Closing as the roles have been updated a long time ago
