### ISSUE TITLE
0434: Out-of-Band Protocols - connection reuse using Connection Protocol

### ISSUE THREAD

**Issue by Toktar** [hyperledger/aries-rfcs#497]
There isn't a special message for a reuse case with Connection protocol. If an invitation contains the handshake protocols, but does not contain a request~attach and there is an existing connection. The receiver should answer:

- If using DID Exchange, respond with the "reuse" message.
- **If using Connections, we can't respond with the "reuse" because 0160: Connection Protocol doesn't contain messages for reusing connection. This additional discussion.**

**Comment by dhh1128** [comment]
Options:

First of all, I would like to say that I hope this case is unusual, because often we are trying to do something more than just connect (so we will have a request~attach). But I acknowledge that there will be cases where this issue arises. When it does, it seems to me that we could solve it in the following ways:

1. Evolve the connection protocol to add the desired message (reuse, I suppse). This would create connection protocol 1.1 and has the obvious drawback that unless others implement it as well, it won't be interoperable. However, maybe interoperability is more important for the normal circumstances where we have request~attach, so the lack of interop in this one narrow case is okay? (Also, how many potential interop targets support the Connection protocol, anyway?)

2. Respond with any message (ACK, trust ping, problem report, or the beginning of a new protocol) where sender = DID of reused connection and parent thread id comes from the invitation. This essentially says, "I'm talking on a channel we've both used before, but I'm letting you know that what I'm now sending is a continuation of an invitation you gave me. You can make the connection because of the thread id." This feels like a reasonable long-term behavior to implement, no matter what protocols are in place. However, it is a new convention that others won't be using, so it has the same interoperability problem as #1.

3. Introduce a new decorator, maybe ~reuse or ~switch_did, that marks a switch from one DID to another. This would be protocol-independent and is similar to a DID rotation header being discussed in DIDCommV2 planning at DIF right now. Again, this doesn't preserve interop very well.

Personally, I like option 1 the best. But none of my ideas solve the interop question. So how important is it to do so?

**Comment by llorllale** [comment]
@swcurran looks OK.

Only minor point is that this `reuse` message will no longer really be "out of band". But I can live with that.

**Comment by swcurran** [comment]
That's what Daniel said :-).  @TelegramSam @andrewwhitehead -- your thoughts?

**Comment by llorllale** [comment]
@swcurran to be clear, I was referring to this:

> Interesting idea. What about moving the reuse message that we put in did-exchange and put it into Out of Band? Then we have it as a generic message for any connection-like protocol, and we can use it without changing connections.

**Comment by swcurran** [comment]
@llorllale  - That's less clear.  Do you want it kept in DID Exchange as well as having it in OOB?  I don't like that idea -- I would want it only on one.

**Comment by llorllale** [comment]
@swcurran I am in agreement with your proposal: extract `reuse` from didexchange and move it into outofband.

**Comment by andrewwhitehead** [comment]
I'm not sure I understand the proposal to move it, the example for a reuse message is this:

```
{
  "@type": "https://didcomm.org/didexchange/1.0/reuse",
  "@id": "12345678900987654321",
  "~thread": {
    "pthid": "<The Parent Thread ID of the Out Of Band Invitation>"
  }
}
```

Since it's already in the context of an OOB message does that boil down to just giving the the message a pthid (or reuse_id or something)?

**Comment by llorllale** [comment]
@andrewwhitehead it would be a `pthid`, but yes - that's what it boils down to. And of course sending this message through the existing didcomm channel

**Comment by swcurran** [comment]
It just means that the @type becomes: `https://didcomm.org/out-of-band/1.0/reuse` and it gets described in the OOB protocol instead of DID Exchange.  That makes it obvious that anyone can use it, including those that support the Connections protocol, without us having to change the connections protocol.  Someone using Connections "in the wild" that handles OOB format invitations can respond with a new connection, or with this new "reuse" message.

**Comment by dhh1128** [comment]
We're achieving zen. I like it. :-)

**Comment by TelegramSam** [comment]
I have a PR in with the proposed changes. Will discuss on today's call.

**Comment by llorllale** [comment]
@Toktar reuse messages were added to RFC 434 a while ago by @TelegramSam - can we close this?

**Comment by TimoGlastra** [comment]
Closing as the `reuse` message has been added to the oob protocol a long time ago
