### ISSUE TITLE
Add RFC for BBS+ Credential Format

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#628]
@TimoGlastra -- do you have a bit of time to take the lead on adding a BBS+ Credential Format RFC?  Presumably it would lean heavily (ideally by reference, not copy and paste) on RFC 593 JSON-LD Cred Format.

Perhaps @llorllale or someone involved in the Aries Framework Go implementation could help with a quick review so we can get this in quickly?

**Comment by TimoGlastra** [comment]
Sure -- However it's still a bit unclear to me what such a RFC should contain. 

One thing that's definitely useful is a guide or point of reference for implementing BBS+ credentials with a pointer to the right specs. 

However I don't think it's beneficial to make it a separate credential format. This adds another format to the registry that agents must support, and that almost exactly matches the already existing format described in RFC0593. e.g. we also don't use a separate attachment format for DIF Presentation Exchange using BBS+ credentials.

So my preference would go to extending RFC0593 to support the requirements for BBS+ credentials (at the moment none, this will change with bound signatures I guess) and then creating a separate RFC that describes the semantics of using BBS+ credentials. This RFC could then also contain details on the PE part of using BBS+ with some conventions.

**Comment by swcurran** [comment]
The RFC just has to say how to use BBS+.  If all that requires is to say "Use this other RFC, but change `json-ld` to `bbs+` and you are done" then that is fine. That can be the starting point and first draft.  I'm guessing it's a little more than that :-).  As you note, even without a format change to the attachment, there is still likely some guidance needed for implementers (now or soon), and this will give us a place to do that.

**Comment by kdenhartog** [comment]
Looking through RFC 593 I'd expect to be able to request a BBS credential that you'd just set to the `proofType` property to be set to `BbsBlsSignature2020` during the issuance flow and `BbsBlsSignatureProof2020` during the verification flow.

In terms of the response, I suppose you could modify `aries/ld-proof-vc-detail@v1.0` to be something like `aries/ld-proof-bbs-vc-detail@v1.0`, but then I'd wonder if you're planning to support things like `aries/ld-proof-ed255192020-vc-detail@v1.0` as well? In my mind, it could be slightly advantageous to specify the format more specifically, but you could just as well branch on the `proof.type` value after decoding the entire credential.

Would it make more sense instead to just provide some examples to RFC0593 about explicit usage of BBS credentials instead of creating a separate RFC for BBS support?

**Comment by swcurran** [comment]
My rational for having them separate is because otherwise we don't have a specific RFC to include in the BBS+ sub-target (purely bureaucratic) and because I expect as we implement BBS+ we'll wind up with more guidance for the implementers.  On the first, it will tell someone that wants to implement BBS+ where to start -- even if it just says, use RFC 593, changing just these values for `proofType`.

**Comment by kdenhartog** [comment]
> My rational for having them separate is because otherwise we don't have a specific RFC to include in the BBS+ sub-target (purely bureaucratic) and because I expect as we implement BBS+ we'll wind up with more guidance for the implementers. On the first, it will tell someone that wants to implement BBS+ where to start -- even if it just says, use RFC 593, changing just these values for `proofType`.

Fair enough. It may be just a simple one, but at least it makes it very clear what someone needs to do in order to support it. All things consider it's probably a better way to approach it than some of the things we've done in the past where we similar but different topics together into common RFCs because we were thinking about both of them at the time. I know I'm guilty of that, so I can see the advantages to it even if it is a very light one for now.
