### ISSUE TITLE
Consider adding new RFC to AIP 2.0 - 0043 Internationalization

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#630]
At the risk of opening up a new AIP 2.0 debate, I think we need to consider adding RFC [0043 Internationalization](https://github.com/hyperledger/aries-rfcs/blob/master/features/0043-l10n/README.md) to AIP 2.0, rationalized by the goal of improving the Mobile Wallet UX.  I'm sure this is a big issue in many jurisdictions, and is certainly a concern in Canada, where anything we roll out MUST support at least our two official languages.

Thoughts?  Is the RFC "good enough"?

@dhh1128 @TelegramSam @troyronda @devin-fisher @llorllale @tmarkovski @nage

**Comment by dhh1128** [comment]
I've long felt like 0043 is too complex. In DIDComm v2 we simplified the mechanism. A simplified version of the mechanism might be worthy of standardizing, but I think 0043 as currently written is a bit too much.

Regardless of the rationale for the feature, there's no point in putting something in an AIP unless there's community will to implement together. So my vote's not very important; it's more important to hear from folks who have mobile apps.

**Comment by swcurran** [comment]
Could you do a quick summary of the difference between this and DIDComm v2?  Is it easier because of the header concept or something more significant?

FWIW -- the BC and Canadian partners hope to soon put a lot more effort into an open source wallet concept and a big reason for that is this issue.  We can't go with just an English/sinvle language wallet.   This includes not only the UI, but the presentation of the schema in a wallet.  We can't just have  the claims of a credential or proof displayed as the technical string (e.g. "last_name", "first_name", "dateOfBirth").  That wont cut it.

**Comment by dhh1128** [comment]
The ticket for simplified i18n support in DIDComm v2 is here: https://github.com/decentralized-identity/didcomm-messaging/issues/152

Re-reading my previous comment, I realize that I gave the impression that the v2 story is a *fait accompli*. Actually it's far from that; it's just something that @TelegramSam pushed on, and I've had one or two discussions with him about it. I believe he wrote up his thinking in a HackMD doc, but I don't see it in the "shared with me" list when I log in there, so we'll have to get him to share it. It hasn't been ratified by any community anywhere...

Anyway, the long and short of it is that we imagined dropping message tables and field-specific decorators; the whole message's locale is declared once, in a header, and any localized fields are also declared. Localized text can be included in this same header. You can still provide sets of translations for multiple langs. Message tables aren't imagined to become irrelevant; we just thought that could be a future, advanced feature.

Regarding translated fields in a credential schema: I think this is somewhat independent of the question of localizing fields in DIDComm messages (since VCs and/or proofs would be attachments, not direct message content). The DIF's presentation exchange format has a stub for i18n support, IIRC, but it may have been scrubbed or ignored in v1 of their spec. There has been some talk by people who tout JSON-LD's localization features, claiming that we have a complete solution to this because of JSON-LD. I think this is a partial misunderstanding. It is true that JSON-LD supports localization, but I don't think it is realistic to apply it to the *content* of fields, only to the *names* of fields. The reason is that I don't believe issuers will be willing to put their names behind translations that don't come from them (imagine a doctor being held accountable for a translation of her exam notes in a language she doesn't even read); I also don't think issuers will be willing to make the effort to issue the content in multiple languages (that is, sign both an English and a French version of the doctor's exam notes). But they probably *would* be willing to say that the field "first_name" in English means "prenom" in French...

**Comment by devin-fisher** [comment]
I'm not sure what adding this to API 2.0 would really mean. Adding localization to a message is optional in the RFC, displaying it would not be a interop question. So supporting this RFC would mean what? That an agent don't fail when the localization fields are present? We already require un-recognized fields to be discard. How we would prove support? What test could we write?

@swcurran Are thinking of adding this to the core target? I thought we had a mobile wallet target but I don't see it. I could be remembering wrong.

**Comment by swcurran** [comment]
@devin-fisher -- Perhaps it is a sub-target, but the intention of the inclusion of the RFC would be that the localization would NOT be ignored but used.  So I guess I would at least update the RFC to say that "support of this RFC implies the processing of the i18n fields".  As a mobile app provider, do you have any plans to add i18n support in your app?

@dhh1128 I believe that anything that can be done in a DIDComm2 header could be done in a decorator in DIDComm1, correct?  So it would largely apply.

@dhh1128 -- I was mostly talking about the names of the claims, not the values.  Agreed that the values can also be a concern, but far less so as they must be signed and as such, the signed data must be shown.

Thanks as well for the note on JSON-LD as I wondered if there was such a concept in that.  I kind of suspected it should be there, but have neither looked for or stumbled across it. If you have any links, that would be appreciated.  I'm aware of the Overlay Capture Architecture ideas around i18n and thought that there must be something similar in JSON-LD land.

**Comment by devin-fisher** [comment]
I can't speak for our product team but I have not seen it on a road map (but road maps can be fairly fluid). I'm sure we will want it in the future. And that future will depend on market demand.

**Comment by dhh1128** [comment]
@swcurran : Here is a link to the JSON-LD i18n info that could help with translating the schemas of VCs: https://json-ld.org/spec/latest/json-ld/#string-internationalization

**Comment by TelegramSam** [comment]
closed per discussion in WG call 20210428.
