### ISSUE TITLE
How to see the reason, why a proof request is not verified

### ISSUE THREAD

**Issue by romanzoun** [hyperledger/aries-rfcs#696]
Hey

We have installed the revocation and it works. So we issue credentials and we have a demo application to login with this credentials via a proof request.

Than we revoce the credentials and the login fails....

state: verified
verified: false --> something went wrong

But how to get a message from aries, that this is because of revoced status of the credentials?

**Comment by kdenhartog** [comment]
This seems like an issue that's more connected to the implementation in use. We haven't defined strong errors for these types of things. I'd suggest raising this error on the repository for the specific implementation you're using instead.

**Comment by swcurran** [comment]
Agreed -- this is an indy-sdk issue and so should be raised there. What you are noting is that the AnonCreds implementation determines if the proof is verifies or not, but if it doesn't, there is no reason given. I don't know if that is by design or a bug.

https://github.com/hyperledger/indy-sdk

**Comment by romanzoun** [comment]
so can I assume, if all my requested attributs are revealed, but its not verified, than the credentials are revoked?

And currently I start the verifier cloudagent with the "--auto-verify-presentation" flag....I saw that I can do this manually and the response contains a property "error_msg" should I give it a try and verify manually, or would it be waste of time?

**Comment by romanzoun** [comment]
> This seems like an issue that's more connected to the implementation in use. We haven't defined strong errors for these types of things. I'd suggest raising this error on the repository for the specific implementation you're using instead.

It's not about the error, more about why it's not verified, like status code in HTTP to classify this. If its an error or just a message, or I catch this and try different stuff is business logic.

**Comment by kdenhartog** [comment]
Yeah the problem is the purpose of this repository is not for working on code and the issue you're having is with the code not how the RFCs are defined from what I can tell. Since not all of the developers who are working on these codebases for these things don't frequent the RFCs repository as much as they would the repositories you should raise this issue with the repository of the codebase you're actually using not in aries-rfc.

From the sounds of the usage of the `--auto-verify-presentation` flag, I'm assuming you're using ACA-py and based on @swcurran response this is something that is actually happening below their implementation in the Indy-SDK. So I'd suggest filing this issue in https://github.com/hyperledger/indy-sdk/issues like he suggested and cross referencing to the ACA-py repository here: https://github.com/hyperledger/aries-cloudagent-python/

**Comment by romanzoun** [comment]
thank you for the advice
