### ISSUE TITLE
DIDComm methods to prevent replay attacks

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-rfcs#96]
As far as I'm aware, the only requirement of content layer messages is that they include an `@type` field. I believe it may be necessary to also require the `@id` field or a timestamp in order to prevent replay attacks. While I'm not able to think of how it could be abused right now because the content is encrypted, I think it would be best practice for us to include something of this nature to prevent this from being combined and abused later.

@TelegramSam can you comment on the requirements of the content layer?
@mikelodder7 any thoughts on this based on what you're aware of?

**Comment by dhh1128** [comment]
Including @id would prevent replay and should be a best practice. Adding a separate nonce when you have @id is redundant and should be avoided. IMO we should not require @id because replay is not necessarily an error.  For example, if I send the same tic-tac-toe move twice, or 200 times, it shouldn't matter. The protocol is idempotent, and it doesn't depend on the @id or a nonce or anything like unto it. Thus, I think reply is a concern for the problem-domain-specific protocols, not for the lower level of DIDComm. But it would be good to add  a comment to the RFC about protocols (0003), suggesting that they require @id if they are worried about replay--and probably a section to the RFC about DIDComm best practices (0074) to the same effect.

**Comment by dhh1128** [comment]
Extra documentation about best practice with `@id` was added in PR #374, which is now merged. Closing issue. Please reopen if you think that's premature.
